default:
  image: "pytorch/pytorch"
  before_script:
    - apt-get update -qq && apt-get install -y -qq texlive-science
    - pip install --upgrade pip
    - pip --version
    - python --version

job:
  script:
    - pip install -e .
    - python setup.py test
